spring:
  datasource:
    oracle:
      url: jdbc:oracle:thin:@localhost:1521/orcl
      username: dmz
      password: zhudao123
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.driver.OracleDriver
    h2:
      url: jdbc:h2:~/H2Data/cboard;AUTO_SERVER=TRUE;LOG=0;UNDO_LOG=0
      username: sa
      password:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: org.h2.Driver
