spring:
  datasource:
    oracle:
      url: jdbc:oracle:thin:@localhost:1521/orcl
      username: dmz
      password: zhudao123
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.driver.OracleDriver
